### PR TITLE
ListView mixin

### PR DESCRIPTION
**Pull request by dmarcelino**
Hey @hiimdoublej,

This PR adds support for CBV ListViews.

Please review.

Cheers

### CODE REVIEW

**Comment by hiimdoublej** [comment]
Merged !

**Comment by dmarcelino** [comment]
Good stuff! Please let me know when you release it.

**Comment by hiimdoublej** [comment]
@dmarcelino the release is here, version `0.0.4`

**Comment by dmarcelino** [comment]
Thanks @hiimdoublej!

**Pull request merged**
