### PR TITLE
Add CBV mixins and Detail view

### PR DESCRIPTION
**Pull request by dmarcelino**
Hello @hiimdoublej 

This PR adds a CBV mixin and a Detail View making it easier to generate structured data from models in CBV Detail views. Using the default settings all it takes is to add an attribute to the model that returns dict with structured data.

Let me know if you want me to make any changes.

Cheers

### CODE REVIEW

**Comment by hiimdoublej** [comment]
Hey man I liked the idea, but could you include some examples in the README ? So that people could use it with ease and will understand the mixin & the view better.

**Comment by dmarcelino** [comment]
Sure, will do so!

**Comment by dmarcelino** [comment]
@hiimdoublej, I've added configuration options and a CBV example to the README. Let me know if you need anything ele. Cheers

**Comment by hiimdoublej** [comment]
looks good to me! Merged! Will make a release on Monday and update the pypi package.

**Comment by hiimdoublej** [comment]
@dmarcelino The new release is up. FYI

**Comment by dmarcelino** [comment]
Hi @hiimdoublej, good stuff! Thanks for the heads up.

I'm working on one more CBV change to make the code more generic. Right now it's focused on `DetailView` and I'm improving the code for `View`, to avoid the attempt to read `self.object`. I'll submit a PR once it's ready.

**Comment by hiimdoublej** [comment]
Alright. I'll be more than happy to review it for you :)

**Pull request merged**
