### PR TITLE
1. added JSON_LD_INDENT settings parameter to prettify output...

### PR DESCRIPTION
**Pull request by gassan**
2. added trailing slash to urls http://schema.org -> http://schema.org/
3. added quotes to script[type] attribute.

and please feel free to discard any changes.

### CODE REVIEW

**Comment by hiimdoublej** [comment]
Dear @gassan , thanks for the PR and I see what you're trying to accomplish. I have no problem with your implementations around this. Just one question, if you're adding structured data onto your site to improve SEO, I think the rising number of line breaks by using indentation are not helping your site in regards of SEO. So could you tell me your reasons behind this change ? Because SEO-wise, it seems a bit paradox with the purpose of this package.

**Comment by gassan** [comment]
Hello @hiimdoublej , I must confess that I did not know anything about possible disadvantages in terms of SEO. The main and only goal is readability during development, no more, no less ;)

**Comment by hiimdoublej** [comment]
@gassan , Your point is made clear. If that's the case, could you kindly modify your change to respect the `settings.DEBUG` option ? Since all you wanted was readability during development, I would like to keep it rendered without additional new lines in production environments for our users.

**Comment by gassan** [comment]
@hiimdoublej, do you think that the default value None (old behavior - no new lines) is not sufficient?

**Comment by hiimdoublej** [comment]
@gassan Yes, I'm suggesting for it to render no newlines if `DEBUG` is turned off.

**Pull request merged**
